apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector: # to match the pod created in clinet-deployment.yaml, so component is web
    component: web
  ports:
    - port: 3000
      targetPort: 3000
