apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: server # to map to server-deployment config file
  ports:
    - port: 5000
      targetPort: 5000
